version: "3.5"
services:
  orion:
    image: fiware/orion
    hostname: orion
    container_name: orion-fiware
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG -noCache
  
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo-Respirar
    ports:
      - "27017:27017" 
    command: --bind_ip_all --smallfiles
    volumes:
      - ./volumes/mongo-db-volume:/data/db

  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0

  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql-db
    container_name: db-mysql1
    environment:
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=12345"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: mysql-admin
    ports:
      - "8080:80"
    environment:
      - "PMA_HOST=mysql-db"
    depends_on:
      - mysql-db
    

volumes:
  mongo-db: ~
  mysql-db: ~