version: "3.5"
services:
  orion:
    image: fiware/orion
    hostname: orion
    container_name: orion-fiware
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG -noCache
  
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo-Respirar
    ports:
      - "27017:27017" 
    command: --bind_ip_all --smallfiles
    volumes:
      - ./volumes/mongo-db-volume:/data/db

  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0

  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql-db
    container_name: db-mysql1
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: mysql-admin
    ports:
      - "8080:80"
    environment:
      - "PMA_HOST=mysql-db"
    depends_on:
      - mysql-db
    
  cygnus:
    image: fiware/cygnus-ngsi
    hostname: cygnus
    container_name: cygnus-fiware
    networks:
      - default
    depends_on:  
      - mysql-db
    ports:
      - "5055:5055"
      - "5080:5080"
    environment:
      - "CYGNUS_MYSQL_HOST=mysql-db"
      - "CYGNUS_MYSQL_PORT=3306"
      - "CYGNUS_MYSQL_USER=root"
      - "CYGNUS_MYSQL_PASS=secret"
      - "CYGNUS_MYSQL_SERVICE_PORT=5055"
      - "CYGNUS_LOG_LEVEL=INFO"
      - "CYGNUS_SERVICE_PORT=5055"
      - "CYGNUS_API_PORT=5080"

volumes:
  mongo-db: ~
  mysql-db: ~